#!/bin/bash

# HRK MPIfR 2026
#
# usage like: source 00_OBS_INFORMATION MSFILENAME CURRENT_DIR
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define MS dataset
DATA_FILE_NAME=$1

# Define the path of the current working directory
WORK_PATH=$2

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR.simg"

# Define path
#
DATA_PATH="/bEDD/MPLUS-DATA/"
CONTAINER_PATH="/bEDD/MPLUS-CONTAINER/"

# Define singularity input 
#
CONTAINER="/bEDD/MPLUS-CONTAINER/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" /work/GET_MS_INFO --DATA_DIR=${DATADIR} --WORK_DIR=${WORKDIR} --MS_FILE=${DATA_FILE_NAME}

