#!/bin/bash

# HRK MPIfR 2026
#
# in bash sehll source FILENAME
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define MS dataset
# DATA_FILE_NAME=$1

# Define the path of the current working directory
# WORK_PATH=$2

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR.simg"

# Define path
#
DATA_PATH="/bEDD/MPLUS-DATA/"
CONT_PATH="/bEDD/MPLUS-CONTAINER/"

# Define singularity input 
#
CONTAINER="${CONT_PATH}/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
singularity shell --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" 
