#!/bin/bash

# HRK MPIfR 2026
#
# usage like: source 02_OBS_DIAGNOSTIC_PLOTS MSFILENAME CURRENT_DIR
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define MS dataset
DATA_FILE=$1

# Define the path of the current working directory
WORK_PATH=$2

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR_SHADEMS.simg"

# Define path
#
DATA_PATH="/bEDD/MPLUS-DATA/"
CONT_PATH="/bEDD/MPLUS-CONTAINER/"

# Define singularity input 
#
CONTAINER="${CONT_PATH}/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
#
singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --xaxis FREQ --yaxis DATA:amp --corr XX,YY --iter-corr --iter-field --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"
